- project/app/admin.py
Thêm trạng thái "Đang liên lạc đội cứu hộ"
Thêm trạng thái "Đội cứu hộ đang tới"
Trạng thái của đội cứu hộ edit được
> Thêm 2 trạng thái 

- project/app/admin.py
- project/app/static/css/custom.css
https://github.com/hailoc12/cuuhomientrung/issues/8
https://github.com/hailoc12/cuuhomientrung/issues/7
> Fix width của một vài column. Chia tỉ lệ table 80% filter 20%

- project/app/utils/export_to_excel.py
> Fix date time in excel file

- project/app/admin.py
https://github.com/hailoc12/cuuhomientrung/issues/11
> Hiển thị số lượng hộ dân đã được cứu 

- project/app/admin.py
Lỗi url không chính xác khi ấn vào link chi tiết của trang thống kê.
> Hotfix issue reusable code for admin: thon, huyen, xa, tinh url.

- docker-compose.yaml
> Fix postgresql docker image issue on Windows

- project/app/models.py
Chặn việc các Text Field blank hoặc null dẫn đến add null value vào các table.
Giữ lại các blank field không quan trọng như note, thôn,..
> Fix empty/null value fields

- project/app/admin.py
Paging Giới hạn 30 records 1 trang
#45
> Pagination

- project/app/admin.py
Reverts Cuuhomientrung/cuuhomientrung#61
> Revert "Pagination"

- .gitignore
- project/app/admin.py
#57 Hỗ trợ trỏ link google map của Xã
Notes: Chưa hỗ trợ trõ link google map của Huyện và Tĩnh, tạm thời hỗ trợ chuyền link sáng site https://vietnamhometown.com.
TODO: Khi nào Huy support Tĩnh và Huyện sẽ cập nhật tiếp.
> chmt-#57 Support to redirect link Google Maps

- .gitignore
- project/app/admin.py
Reverts Cuuhomientrung/cuuhomientrung#65
> Revert "chmt-#57 Support to redirect link Google Maps"

- project/static/admin/css/responsive.css
Because of lost code when do hotfix on production
old PR: #21
> Move filter area to top page on mobile responsive

- project/app/static/css/custom.css
Update some column width on table
issue #83
> Update table style include note column #83

- project/app/static/css/custom.css
- project/templates/admin/change_list.html
It should show like:
- Collapse (when user enter the page): 
- Open it
> Collapse filter bar on mobile #91

- project/app/admin.py
Query status=1 (Hộ cần cấp cứu) => status_id=3
> Fix status model update make old query fail

- project/app/admin.py
- project/app/models.py
- project/app/settings.py
**Changes**
- Sửa dropdown form chọn Tỉnh, Huyện, Xã trong trang Hộ Dân và Cứu Hộ: Chọn tỉnh xong mới chọn huyện, chọn huyện xong mới chọn xã, danh sách xã và huyện hiển thị theo lựa chọn tỉnh, huyện trước đó.
> Fix location selection in HoDan and CuuHo

- project/app/admin.py
Sửa list_display function để optimize query_set result trc đó.
Fix Huyện + Tỉnh admin ko sort theo total Hộ dân
> Fix Huyen, Tinh admin not ordered by total hodan can cap cuu

- project/app/admin.py
- project/app/models.py
> Rearrange Menu

- project/app/index.py
- project/templates/home_index.html
> Highlight các con số 

- Dockerfile
- SETUP-DOCKER.md
- docker-compose.yaml
Update dockerfile alongside with new webpack dev
> Update docker file

- project/app/admin.py
- requirements.txt
> Issue 132 search in Dropdown

- project/app/admin.py
- project/app/models.py
Tôi thêm vào trạng thái 0 == Chưa xác minh. Nếu không có trạng thái này thì Django sẽ không hiển thị dropdown.
Vui lòng cho tôi biết nếu tôi có làm gì sai.
> Fix #165: Thêm dropdown cho [tình trạng] trong trang [Tình nguyện viên]

- Dockerfile
Correct command npm instal to npm install
> Correct typo command npm instal

- webpack.config.js
Có hai commit:
1. ce5941a Prettify webpack.config.js
2. a0b14c5 Simplify webpack.config.js
> Sửa lỗi và đơn giản hóa webpack.config.js

- project/app/models.py
- project/app/settings.py
Sửa một số lỗi nho nhỏ
1. 3e8899c Remove hook in project/app/models.py
2. 4202918 Fix STATICFILES_DIRS in project/app/settings.py
> Sửa một số lỗi ở models.py và settings.py

- project/app/ho_dan_views.py
- project/app/models.py
- project/app/utils/export_to_excel.py
- project/templates/ho_dan_index.html
HODAN_STATUS_NEW and HODAN_STATUS are deprecated -> Remove
> Xoá dict trạng thái không dùng

- project/app/admin.py
- project/app/utils/safe_url.py
Otherwise input URLs such as javascript:alert(1) can lead to XSS.
> Sanitize news URLs.

- project/app/static/webpack_sources/scss/pages/_homepage.scss
- project/templates/home_index.html
> Fixed issue 216

- project/app/ho_dan_views.py
- project/templates/ho_dan_index.html
> Fixes issue #223

- project/app/index.py
Hiện tại bảng thống kê bị hiển thị sai, tên Tỉnh và url không khớp nhau.
**Problem**
Độ dài của các list `hodan_can_cuu`, `hodan_da_cuu` và `cuuho_by_tinh` không tương xứng và các phần tử không hoàn toàn giống nhau, nên dù có được sort theo cùng thứ tự nhưng data lại khác nhau khiến việc update context bị sai.
- Ví dụ:
```python
hodan_can_cuu = [ 
{
"tinh_id": 1,
....
},
{
"tinh_id": 2,
....
}
]
hodan_da_cuu = [ 
{
"tinh_id": 1,
....
},
{
"tinh_id": 3,
....
}
]
```
Phải sửa lại logic để đảm bảo lấy ra đc đúng giá trị
> Hot fix bảng thống kê

- project/templates/home_index.html
> Fixed issue #237

- project/templates/home_index.html
> Fixed issue #242
